enum mname {
	name[50],
	by[30]
};

new MapName[][mname]=
{
	{"Trevortex","Erza."},
	{"De_Dust_2","JimmySpaceTravel1337"},
	{"The_Caribbeans","JimmySpaceTravel1337"},
	{"Reckless_Bikers","Louay."},
	{"Fat_N_Furious_2012","JimmySpaceTravel1337"},
	{"Fat_N_Furious_Beneath_The_Wheel","JimmySpaceTravel1337"},
	{"Back_To_Glen_Park","iJumbo"},
	{"To_The_Clown","Sasuke_Uchiha"},
	{"Desert_Storm","JimmySpaceTravel1337"},
	{"Grand_Theft_Shamal","JimmySpaceTravel1337"}
};